server:
  port: 90


spring:
  application:
    name: service-invoker

#eureka:
#  client:
#    serviceUrl:
#      # 將服務註冊到eureka-server
#      defaultZone: http://localhost:8781/eureka/,http://localhost:8782/eureka/
#    fetch-registry: true
#    registry-fetch-interval-seconds: 16
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 8
#    lease-expiration-duration-in-seconds: 24

