#單機
#server:
#  port: 8781
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 5000



#兩台eureka server ha
spring:
  application:
      name: eureka-server
#  security:
#    user:
#      name: jerry
#      password: jerry

server:
  port: 8781
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8782/eureka




